### PR TITLE
Update appVersion to v0.52.0

### PR DESCRIPTION
**Pull request by fhielpos**

### CODE REVIEW

**Comment by stone-z** [comment]
Why? https://github.com/giantswarm/trivy-app/blob/main/helm/trivy/charts/trivy/Chart.yaml#L4

**Comment by fhielpos** [comment]
Because this chart has been abandoned upstream:
https://github.com/aquasecurity/trivy/tree/main/helm/trivy

I am wondering at what point we should just enable the trivy server provided by trivy-operator.

**Comment by stone-z** [comment]
But are we actually running that app version? Like our chart already drifted from upstream you mean?

**Comment by Strigix** [comment]
That's correct.
If we were to use the defaults from upstream, we would be running version 37, we're now running 50.1 IIRC.

**Review by Strigix — APPROVED** [review]

**Pull request merged**
