### PR TITLE
Update Trivy to upstream app version v0.30.4

### PR DESCRIPTION
**Pull request by fhielpos**
### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

**Important:** After this PR is tested and approved, ensure you "Squash and Merge" _unless you are updating a subtree_. The release automation in use on this repository relies on squashing, but git subtrees will be lost if squashed. This repo allows both, so you may need to change the merge type when merging.

### CODE REVIEW

**Comment by fhielpos** [comment]
> Do we also need to change / remove this?
> 
> https://github.com/giantswarm/trivy-app/blob/e55bb5445bc1bc2ccc53ae7a69b2aa9c7de0256e/helm/trivy-app/values.yaml#L13

Any reason why we set the value instead of using the native template?
https://github.com/giantswarm/trivy-app/blob/2bc7f9de6ee5c08d15e35f76dc4413f4b035349a/helm/trivy-app/charts/trivy/templates/_helpers.tpl#L53

**Comment by fhielpos** [comment]
Okay, seems that they added that some versions ago after we were already using the values file. I will remove it and test how it goes without it.

**Review by stone-z — APPROVED** [review]
Bam :+1:

**Comment by stone-z** [comment]
Remember not to squash the subtree

**Pull request merged**
